"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = require("@angular/core");
var CommonFooter = (function () {
    function CommonFooter() {
    }
    CommonFooter.prototype.messageTyped = function (e) {
        console.log(e);
    };
    CommonFooter.prototype.ngOnInit = function () {
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    };
    CommonFooter = __decorate([
        core_1.Component({
            selector: 'common-footer',
            styles: ["\n    .top-menu a{\n      color: green;\n    }\n\n    footer{\n\n      background: #414042;\n      color: white;\n    /*  border-top: 8px solid #53536a; */\n    }\n    .copyright-line{\n      border-top: 1px solid #f1f1f1; margin-left: 2%; margin-right: 2%; margin-top: 5px;padding-top: 5px;\n\n    }\n    .btn-xs{\n      padding:10px;\n      margin: 1px;\n    }\n    .width-full{\n      width: 100%;\n    }\n\n    .item {\n      display:inline-block;\n  }\n  .flex, .flexcenter {\n  display: -webkit-box;\n  display: -moz-box;\n  display: -ms-flexbox;\n  display: -webkit-flex;\n  display: flex;\n}\n\n.flexcenter {\n  justify-content: center;\n}\n\n.sm-link {\n  margin: 0 15px;\n}\n\n.sm {\n  -webkit-transition: all 0.5s ease-in-out;\n  -moz-transition: all 0.5s ease-in-out;\n  -o-transition: all 0.5s ease-in-out;\n  transition: all 0.5s ease-in-out;\n  padding: .2em 0;\n  width: 1.8em;\n  border-radius: 4px;\n  background-size: 100% 200%;\n  background-position: 0 20%;\n  background-repeat: no-repeat;\n  text-align: center;\n  color: whitesmoke;\n  font-size: 1.2em;\n  text-shadow: 4px 2px 4px rgba(0, 0, 0, 0.3);\n  -webkit-box-shadow: 4px 2px 10px 0px rgba(50, 50, 50, 0.6);\n  -moz-box-shadow: 4px 2px 10px 0px rgba(50, 50, 50, 0.6);\n  box-shadow: 4px 2px 10px 0px rgba(50, 50, 50, 0.6);\n}\n.sm:hover {\n  background-position: 0 100%;\n  text-shadow: 4px 2px 4px rgba(0, 0, 0, 0.7);\n}\n\n.twitter {\n  background-image: -webkit-linear-gradient(#e8e6e6 50%, #e8e6e6 50%);\n  background-image: -o-linear-gradient(#e8e6e6 50%, #e8e6e6 50%);\n  background-image: -moz-linear-gradient(#e8e6e6 50%, #e8e6e6 50%);\n  background-image: linear-gradient(#e8e6e6 50%, #e8e6e6 50%);\n}\n\n.facebook {\n  background-image: -webkit-linear-gradient(#e8e6e6 50%, #e8e6e6 50%);\n  background-image: -o-linear-gradient(#e8e6e6 50%, #e8e6e6 50%);\n  background-image: -moz-linear-gradient(#e8e6e6 50%, #e8e6e6 50%);\n  background-image: linear-gradient(#e8e6e6 50%, #e8e6e6 50%);\n}\n\n.linkedin {\n  background-image: -webkit-linear-gradient(#e8e6e6 50%, #e8e6e6 50%);\n  background-image: -o-linear-gradient(#e8e6e6 50%, #e8e6e6 50%);\n  background-image: -moz-linear-gradient(#e8e6e6 50%, #e8e6e6 50%);\n  background-image: linear-gradient(#e8e6e6 50%, #e8e6e6 50%);\n}\n.smicons{\n  display: inline-flex;\n  @extend .flexcenter;\n  margin-left:-15px;\n  padding-top:4px;\n}\n\n\n\n  "],
            template: "\n\n\n<footer>\n<div style=\"height:20px;\"></div>\n<div>\n<div class=\"row\">\n <div class=\"col-md-3\">\n </div>\n <div class=\"col-md-7\">\n <div class=\"row\">\n  <div class=\"col-md-4\">\n   <h4 style=\"color:white !important;\"> Learn More </h4>\n   <div style=\"height:10px; \"></div>\n   <ul>\n     <li ><a style=\"color:white;\"  href=\"#page-about\" >About Us</a></li>\n     <li style=\"margin-top:4px;\"><a style=\"color:white;\" href=\"#page-ratings\">Ratings</a></li>\n     <li style=\"margin-top:4px;\"><a style=\"color: white;\" href=\"#page-faq\" >FAQ</a></li>\n\n\n    </ul>\n   </div>\n   <div class=\"col-md-4\">\n    <h4 style=\"color:white !important;\"> Stay connected </h4>\n    <ul>\n      <li style=\"padding-top:12px;\"><input id=\"Email\" name=\"Email\" placeholder=\"Enter your email\" maxlength=\"255\" type=\"\" style=\"width: 144px;\"></li>\n      <li style=\"margin-top:4px;\">\n      <button type=\"button\" class=\"btn btn-sm btn-outline-primary\" ripple-radius style=\"width: 144px;border-color: #ffffff !important;margin-left: 0px;color:#ffffff !important;font-size:12px;\">SIGN UP</button>\n\n      </li>\n     </ul>\n   </div>\n   <div class=\"col-md-4\">\n    <h4 style=\"color:white !important;\"> Support </h4>\n    <div style=\"height:10px; \"></div>\n    <ul>\n      <li style=\"margin-top:-4px;\"><a style=\"color: white;\" href=\"#page-contact\">Contact Us</a></li>\n        <li style=\"margin-top:4px;\"><a style=\"color: white;font-weight:700;\" href=\"#page-contact\">Follow Us</a></li>\n      <li>\n      <div class=\"wrapper smicons\">\n      <a class=\"sm-link\" href=\"#\">\n        <div class=\"sm twitter\" title=\"Twitter\" data-toggle=\"tooltip\" data-placement=\"bottom\">\n        <i class=\"fa fa-twitter\" style=\"color:#333030;\"></i>\n        </div>\n      </a>\n\n      <a class=\"sm-link\" href=\"#\">\n        <div class=\"sm facebook\" title=\"Facebook\" data-toggle=\"tooltip\" data-placement=\"bottom\">\n          <i class=\"fa fa-facebook\" style=\"color:#333030;\"></i>\n        </div>\n      </a>\n\n      <a class=\"sm-link\" href=\"#\">\n        <div class=\"sm linkedin\" title=\"Linkedin\" data-toggle=\"tooltip\" data-placement=\"bottom\" >\n          <i class=\"fa fa-linkedin\" style=\"color:#333030;\"></i>\n        </div>\n      </a>\n      </div>\n\n      </li>\n\n     </ul>\n   </div>\n  </div>\n </div>\n <div class=\"col-md-4\">\n </div>\n</div>\n\n</div><!-- margin 20% -->\n\n\n\n\n\n<div style=\"height:40px;\"></div>\n<div align=\"center\" style=\"background:#221f20;padding:15px 10px 0px 10px;\" class=\"\">\n&copy; 2017 GBCI\n<div style=\"height:20px;\"></div>\n</div>\n\n</footer>\n\n<chat-box (message)=\"messageTyped($event)\"></chat-box>\n\n  ",
        })
    ], CommonFooter);
    return CommonFooter;
}());
exports.CommonFooter = CommonFooter;
